<!doctype html>
<html class="no-js">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="keywords" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>API DOCUMENT</title>

  <meta name="renderer" content="webkit">
  <meta http-equiv="Cache-Control" content="no-siteapp"/>

  <link rel="stylesheet" href="//cdn.amazeui.org/amazeui/2.7.2/css/amazeui.min.css">
  <link rel="stylesheet" href="/assets/stylesheets/doc.css">
</head>
<body>

<header class="am-g my-head">
  <div class="am-u-sm-12 am-article">
    <h1 class="am-article-title">API文档中心</h1>
    <p class="am-article-meta">XXX科技有限公司</p>
  </div>
</header>
<hr class="am-article-divider"/>
<div class="am-g am-g-fixed">
  <div class="am-u-md-9 am-u-md-push-3">
    <div class="am-g">
      <div class="am-u-sm-11 am-u-sm-centered" id="api-content">Loading ...</div>
    </div>
  </div>
  <div class="am-u-md-3 am-u-md-pull-9 my-sidebar">
    <div class="am-offcanvas" id="sidebar">
      <div class="am-offcanvas-bar">
        <ul class="am-nav" id="api-sidebar">
          <li class="am-nav-header">API文档</li>
          <li><a href="#assets/documents/README">简介</a></li>
          <li><a href="#assets/documents/API概览">API概览</a></li>
          <li class="am-nav-header">调用方式</li>
          <li><a href="#assets/documents/请求结构">请求结构</a></li>
          <li><a href="#assets/documents/接口鉴权">接口鉴权</a></li>
          <li><a href="#assets/documents/公共参数">公共参数</a></li>
          <li><a href="#assets/documents/返回值">返回值</a></li>
          <li><a href="#assets/documents/示例代码">示例代码</a></li>
          <li class="am-nav-header">接口列表</li>
          <li><a href="#assets/documents/测试接口">测试接口</a></li>
        </ul>
      </div>
    </div>
  </div>
  <a href="#sidebar" class="am-btn am-btn-sm am-btn-success am-icon-bars am-show-sm-only my-button" data-am-offcanvas><span class="am-sr-only">侧栏导航</span></a>
</div>

<footer class="my-footer">
  <p><small>© Copyright XXX. 2016.</small></p>
</footer>

<script src="//libs.baidu.com/jquery/1.11.3/jquery.min.js"></script>
<script src="//cdn.amazeui.org/amazeui/2.7.2/js/amazeui.min.js"></script>
<script src="//cdn.bootcss.com/marked/0.3.6/marked.min.js"></script>
<script src="/assets/javascripts/doc.js"></script>
</body>
</html>